name: Send a HTTP Request when new RSS item is detected
on:
  rss:
    url: 
      - https://feed43.com/4013128006045655.xml
jobs:
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request      
        uses: actionsflow/axios@main
        with:
          url: {{ secrets.FEISHU_BOT_FAST }}
          method: POST
          body: |
            {
              "msg_type":"text", 
              "content":{"text": "${{on.rss.outputs.title}}\n${{on.rss.outputs.link}}(from github.com)"}
            }
